# Developing an AI application

Going forward, AI algorithms will be incorporated into more and more everyday applications. For example, you might want to include an image classifier in a smart phone app. To do this, you'd use a deep learning model trained on hundreds of thousands of images as part of the overall application architecture. A large part of software development in the future will be using these types of models as common parts of applications. 

In this project, you'll train an image classifier to recognize different species of flowers. You can imagine using something like this in a phone app that tells you the name of the flower your camera is looking at. In practice you'd train this classifier, then export it for use in your application. We'll be using [this dataset](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html) of 102 flower categories, you can see a few examples below. 

<img src='https://github.com/laknath/pytorch_challenge/blob/master/assets/Flowers.png?raw=1' width=500px>

The project is broken down into multiple steps:

* Load and preprocess the image dataset
* Train the image classifier on your dataset
* Use the trained classifier to predict image content

We'll lead you through each part which you'll implement in Python.

When you've completed this project, you'll have an application that can be trained on any set of labeled images. Here your network will be learning about flowers and end up as a command line application. But, what you do with your new skills depends on your imagination and effort in building a dataset. For example, imagine an app where you take a picture of a car, it tells you what the make and model is, then looks up information about it. Go build your own dataset and make something new.

First up is importing the packages you'll need. It's good practice to keep all the imports at the beginning of your code. As you work through this notebook and find you need to import a package, make sure to add the import up here.

In [ ]:
!pip install torch torchvision

In [130]:
# Imports here
import torch
from torchvision import datasets, transforms, models
from torch import nn
from torch import optim
import matplotlib.pyplot as plt
import time

%matplotlib inline


## Load the data

Here you'll use `torchvision` to load the data ([documentation](http://pytorch.org/docs/0.3.0/torchvision/index.html)). You can [download the data here](https://s3.amazonaws.com/content.udacity-data.com/courses/nd188/flower_data.zip). The dataset is split into two parts, training and validation. For the training, you'll want to apply transformations such as random scaling, cropping, and flipping. This will help the network generalize leading to better performance. If you use a pre-trained network, you'll also need to make sure the input data is resized to 224x224 pixels as required by the networks.

The validation set is used to measure the model's performance on data it hasn't seen yet. For this you don't want any scaling or rotation transformations, but you'll need to resize then crop the images to the appropriate size.

The pre-trained networks available from `torchvision` were trained on the ImageNet dataset where each color channel was normalized separately. For both sets you'll need to normalize the means and standard deviations of the images to what the network expects. For the means, it's `[0.485, 0.456, 0.406]` and for the standard deviations `[0.229, 0.224, 0.225]`, calculated from the ImageNet images.  These values will shift each color channel to be centered at 0 and range from -1 to 1.

In [2]:
data_dir = './input/flower_data'
train_dir = data_dir + '/train'
valid_dir = data_dir + '/valid'

In [3]:
# TODO: Define your transforms for the training and validation sets
normalize = transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
train_transforms = transforms.Compose([transforms.Resize(255),
                                       transforms.RandomHorizontalFlip(),
                                       transforms.RandomRotation(10),
                                       transforms.CenterCrop(224), #
                                       transforms.ToTensor(),
                                       normalize]) 

val_transforms = transforms.Compose([transforms.Resize(255),
                                      transforms.CenterCrop(224),
                                      transforms.ToTensor(),
                                      normalize])

# TODO: Load the datasets with ImageFolder
train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)
val_dataset = datasets.ImageFolder(valid_dir, transform=val_transforms)


# TODO: Using the image datasets and the trainforms, define the dataloaders
trainloader = torch.utils.data.DataLoader(train_dataset, batch_size=64, shuffle=True)
valloader = torch.utils.data.DataLoader(val_dataset, batch_size=64, shuffle=True)

### Label mapping

You'll also need to load in a mapping from category label to category name. You can find this in the file `cat_to_name.json`. It's a JSON object which you can read in with the [`json` module](https://docs.python.org/2/library/json.html). This will give you a dictionary mapping the integer encoded categories to the actual names of the flowers.

In [4]:
import json

with open('cat_to_name.json', 'r') as f:
    cat_to_name = json.load(f)

In [54]:
cat_to_name
n_classes = max(list(map(int, cat_to_name.keys())))
n_classes

102

In [41]:
train_dataset.classes
train_dataset.class_to_idx
#val_dataset.class_to_idx

{'1': 0,
 '10': 1,
 '100': 2,
 '101': 3,
 '102': 4,
 '11': 5,
 '12': 6,
 '13': 7,
 '14': 8,
 '15': 9,
 '16': 10,
 '17': 11,
 '18': 12,
 '19': 13,
 '2': 14,
 '20': 15,
 '21': 16,
 '22': 17,
 '23': 18,
 '24': 19,
 '25': 20,
 '26': 21,
 '27': 22,
 '28': 23,
 '29': 24,
 '3': 25,
 '30': 26,
 '31': 27,
 '32': 28,
 '33': 29,
 '34': 30,
 '35': 31,
 '36': 32,
 '37': 33,
 '38': 34,
 '39': 35,
 '4': 36,
 '40': 37,
 '41': 38,
 '42': 39,
 '43': 40,
 '44': 41,
 '45': 42,
 '46': 43,
 '47': 44,
 '48': 45,
 '49': 46,
 '5': 47,
 '50': 48,
 '51': 49,
 '52': 50,
 '53': 51,
 '54': 52,
 '55': 53,
 '56': 54,
 '57': 55,
 '58': 56,
 '59': 57,
 '6': 58,
 '60': 59,
 '61': 60,
 '62': 61,
 '63': 62,
 '64': 63,
 '65': 64,
 '66': 65,
 '67': 66,
 '68': 67,
 '69': 68,
 '7': 69,
 '70': 70,
 '71': 71,
 '72': 72,
 '73': 73,
 '74': 74,
 '75': 75,
 '76': 76,
 '77': 77,
 '78': 78,
 '79': 79,
 '8': 80,
 '80': 81,
 '81': 82,
 '82': 83,
 '83': 84,
 '84': 85,
 '85': 86,
 '86': 87,
 '87': 88,
 '88': 89,
 '89': 90,
 '9': 91,
 '90

# Building and training the classifier

Now that the data is ready, it's time to build and train the classifier. As usual, you should use one of the pretrained models from `torchvision.models` to get the image features. Build and train a new feed-forward classifier using those features.

We're going to leave this part up to you. If you want to talk through it with someone, chat with your fellow students! You can also ask questions on the forums or join the instructors in office hours.

Refer to [the rubric](https://review.udacity.com/#!/rubrics/1663/view) for guidance on successfully completing this section. Things you'll need to do:

* Load a [pre-trained network](http://pytorch.org/docs/master/torchvision/models.html) (If you need a starting point, the VGG networks work great and are straightforward to use)
* Define a new, untrained feed-forward network as a classifier, using ReLU activations and dropout
* Train the classifier layers using backpropagation using the pre-trained network to get the features
* Track the loss and accuracy on the validation set to determine the best hyperparameters

We've left a cell open for you below, but use as many as you need. Our advice is to break the problem up into smaller parts you can run separately. Check that each part is doing what you expect, then move on to the next. You'll likely find that as you work through each part, you'll need to go back and modify your previous code. This is totally normal!

When training make sure you're updating only the weights of the feed-forward network. You should be able to get the validation accuracy above 70% if you build everything right. Make sure to try different hyperparameters (learning rate, units in the classifier, epochs, etc) to find the best model. Save those hyperparameters to use as default values in the next part of the project.

In [123]:
# TODO: Build and train your network

# https://pytorch.org/docs/0.3.0/torchvision/models.html#id2
# resnet152
# densenet121
# vgg19_bn

model = models.resnet152(pretrained=True)
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=F

In [86]:
for param in model.parameters():
    param.requires_grad = False

from collections import OrderedDict
classifier = nn.Sequential(OrderedDict([
                          ('fc1', nn.Linear(25088, 4096)),
                          ('relu1', nn.ReLU()),
                          ('dropout1', nn.Dropout(p=0.5)),
                          ('fc2', nn.Linear(4096, 4096)),
                          ('relu2', nn.ReLU()),
                          ('dropout2', nn.Dropout(p=0.5)),
                          ('fc3', nn.Linear(4096, n_classes)),
                          ('output', nn.LogSoftmax(dim=1))
                          ]))
    
model.classifier = classifier
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=F

#### Using VGG as the base model

In [58]:
vgg16 = models.vgg16(pretrained=True)

for param in vgg16.parameters():
    param.requires_grad = False

n_inputs = vgg16.classifier[6].in_features

# add last linear layer (n_inputs -> 5 flower classes)
# new layers automatically have requires_grad = True
last_layer = nn.Linear(n_inputs, n_classes)
vgg16.classifier[6] = last_layer

for param in resnet152.classifier.parameters():
    param.requires_grad = True

model = vgg16
model

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (17): Conv2d

#### Using Resnet as the base model

In [138]:
resnet152 = models.resnet152(pretrained=True)

for param in resnet152.parameters():
    param.requires_grad = False

n_inputs = resnet152.fc.in_features

# add last linear layer (n_inputs -> 5 flower classes)
# new layers automatically have requires_grad = True
last_layer = nn.Sequential(OrderedDict([
                          ('fc1', nn.Linear(n_inputs, 1024)),
                          ('relu', nn.ReLU()),
                          ('fc2', nn.Linear(1024, n_classes)),
                          ('output', nn.LogSoftmax(dim=1))
                          ]))

resnet152.fc = last_layer

for param in resnet152.fc.parameters():
    param.requires_grad = True

model = resnet152

model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=F

In [76]:
epochs = 3
print_every = 10
lr = 0.003
# device = "cpu" # cuda

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# loss function
criterion = nn.NLLLoss()
# optimizer
optimizer = optim.Adam(model.fc.parameters(), lr=lr)

In [77]:
model.to(device)
model.train()    

for epoch in range(epochs):
   
    running_loss = 0
    for batch, (inputs, labels) in enumerate(trainloader):

        print("Batch {0}, length {1}".format(batch+1, len(labels)))
        # Move input and label tensors to the GPU
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()

        start = time.time()

        logps = model.forward(inputs)
        loss = criterion(logps, labels)
        loss.backward()
        
        optimizer.step()

        running_loss += loss.item()
                
        # Calculate accuracy
        ps = torch.exp(logps)
        top_p, top_class = ps.topk(1, dim=1)
        equals = top_class == labels.view(*top_class.shape)
        training_accuracy = torch.mean(equals.type(torch.FloatTensor)).item()        
        print("Training accuracy {0}; loss= {1}; Time per batch: {2:.2f} seconds".
              format(training_accuracy, loss, (time.time() - start)))
    
        if (batch + 1) % print_every == 0:
            val_loss = 0
            accuracy = 0
            model.eval()
            with torch.no_grad():
                for val_batch, (inputs, labels) in enumerate(valloader):
                    print("Val Batch {0}, length {1}".format(val_batch+1, len(labels)))
                    
                    inputs, labels = inputs.to(device), labels.to(device)
                    logps = model.forward(inputs)
                    batch_loss = criterion(logps, labels)
                    
                    val_loss += batch_loss.item()
                    
                    # Calculate accuracy
                    ps = torch.exp(logps)
                    top_p, top_class = ps.topk(1, dim=1)
                    equals = top_class == labels.view(*top_class.shape)
                    accuracy += torch.mean(equals.type(torch.FloatTensor)).item()
                    
            print("Epoch {0}/{1}; " \
                  "Train loss: {2:.3f}; " \
                  "Val loss: {3:.3f}; "
                  "Val accuracy: {4:.3f}" \
                  .format(epoch+1, epochs, running_loss/print_every, 
                          val_loss/len(valloader), accuracy/len(valloader)))
            model.train()    

Batch 1, length 64
Training accuracy 0.0; loss= 4.609948635101318; Time per batch: 30.85 seconds
Batch 2, length 64
Training accuracy 0.03125; loss= 7.314370155334473; Time per batch: 30.34 seconds
Batch 3, length 64
Training accuracy 0.078125; loss= 7.1041364669799805; Time per batch: 30.49 seconds
Batch 4, length 64
Training accuracy 0.015625; loss= 6.671851634979248; Time per batch: 30.70 seconds
Batch 5, length 64
Training accuracy 0.015625; loss= 5.859113693237305; Time per batch: 30.49 seconds
Batch 6, length 64
Training accuracy 0.046875; loss= 5.174648761749268; Time per batch: 30.92 seconds
Batch 7, length 64
Training accuracy 0.015625; loss= 4.689922332763672; Time per batch: 30.74 seconds
Batch 8, length 64
Training accuracy 0.0; loss= 4.750618934631348; Time per batch: 30.65 seconds
Batch 9, length 64
Training accuracy 0.03125; loss= 4.711737155914307; Time per batch: 30.90 seconds
Batch 10, length 64
Training accuracy 0.046875; loss= 4.581082820892334; Time per batch: 30.4

Batch 62, length 64
Training accuracy 0.46875; loss= 2.492140054702759; Time per batch: 30.53 seconds
Batch 63, length 64
Training accuracy 0.453125; loss= 2.428887367248535; Time per batch: 30.52 seconds
Batch 64, length 64
Training accuracy 0.3125; loss= 2.8985090255737305; Time per batch: 30.50 seconds
Batch 65, length 64
Training accuracy 0.4375; loss= 2.2492916584014893; Time per batch: 30.37 seconds
Batch 66, length 64
Training accuracy 0.359375; loss= 2.534078359603882; Time per batch: 30.42 seconds
Batch 67, length 64
Training accuracy 0.34375; loss= 2.349597215652466; Time per batch: 30.92 seconds
Batch 68, length 64
Training accuracy 0.40625; loss= 2.1813483238220215; Time per batch: 30.98 seconds
Batch 69, length 64
Training accuracy 0.5; loss= 2.3488874435424805; Time per batch: 30.24 seconds
Batch 70, length 64
Training accuracy 0.375; loss= 2.435412883758545; Time per batch: 30.42 seconds
Val Batch 1, length 64
Val Batch 2, length 64
Val Batch 3, length 64
Val Batch 4, le

Val Batch 1, length 64
Val Batch 2, length 64
Val Batch 3, length 64
Val Batch 4, length 64
Val Batch 5, length 64
Val Batch 6, length 64
Val Batch 7, length 64
Val Batch 8, length 64
Val Batch 9, length 64
Val Batch 10, length 64
Val Batch 11, length 64
Val Batch 12, length 64
Val Batch 13, length 50
Epoch 2/3.. Train loss: 3.049.. Val loss: 1.096.. Val accuracy: 0.705
Batch 21, length 64
Training accuracy 0.65625; loss= 1.481552004814148; Time per batch: 30.73 seconds
Batch 22, length 64
Training accuracy 0.65625; loss= 1.1835237741470337; Time per batch: 30.88 seconds
Batch 23, length 64
Training accuracy 0.671875; loss= 1.312930941581726; Time per batch: 30.71 seconds
Batch 24, length 64
Training accuracy 0.765625; loss= 1.035648226737976; Time per batch: 30.51 seconds
Batch 25, length 64
Training accuracy 0.6875; loss= 1.3453340530395508; Time per batch: 30.52 seconds
Batch 26, length 64
Training accuracy 0.65625; loss= 1.31198251247406; Time per batch: 30.88 seconds
Batch 27, len

Batch 79, length 64
Training accuracy 0.703125; loss= 0.9820769429206848; Time per batch: 30.74 seconds
Batch 80, length 64
Training accuracy 0.78125; loss= 0.8644077777862549; Time per batch: 30.49 seconds
Val Batch 1, length 64
Val Batch 2, length 64
Val Batch 3, length 64
Val Batch 4, length 64
Val Batch 5, length 64
Val Batch 6, length 64
Val Batch 7, length 64
Val Batch 8, length 64
Val Batch 9, length 64
Val Batch 10, length 64
Val Batch 11, length 64
Val Batch 12, length 64
Val Batch 13, length 50
Epoch 2/3.. Train loss: 9.708.. Val loss: 0.733.. Val accuracy: 0.804
Batch 81, length 64
Training accuracy 0.703125; loss= 1.1977243423461914; Time per batch: 30.93 seconds
Batch 82, length 64
Training accuracy 0.640625; loss= 1.126045823097229; Time per batch: 30.93 seconds
Batch 83, length 64
Training accuracy 0.71875; loss= 1.2490386962890625; Time per batch: 30.71 seconds
Batch 84, length 64
Training accuracy 0.8125; loss= 0.8417697548866272; Time per batch: 30.73 seconds
Batch 85

KeyboardInterrupt: 

## Save the checkpoint

Now that your network is trained, save the model so you can load it later for making predictions. You probably want to save other things such as the mapping of classes to indices which you get from one of the image datasets: `image_datasets['train'].class_to_idx`. You can attach this to the model as an attribute which makes inference easier later on.

```model.class_to_idx = image_datasets['train'].class_to_idx```

Remember that you'll want to completely rebuild the model later so you can use it for inference. Make sure to include any information you need in the checkpoint. If you want to load the model and keep training, you'll want to save the number of epochs as well as the optimizer state, `optimizer.state_dict`. You'll likely want to use this trained model in the next part of the project, so best to save it now.

In [150]:
# TODO: Save the checkpoint 

checkpoint_name = 'checkpoint_1.pth'

checkpoint = {'input_size': 224*224,
              'output_size': 102,
              'train_batchsize': trainloader.batch_size,
              'val_batchsize': valloader.batch_size,
              'epochs': epochs,
              'lr': lr,
              'model_class': model.__class__,
              'model_name': 'resnet152',
              'classifier': model.fc.state_dict(),
              'state_dict': model.state_dict(),
              'class_to_idx': train_dataset.class_to_idx,
              'optimizer': optimizer.state_dict
             }

torch.save(model.state_dict, checkpoint_name)

## Loading the checkpoint

At this point it's good to write a function that can load a checkpoint and rebuild the model. That way you can come back to this project and keep working on it without having to retrain the network.

In [153]:
# TODO: Write a function that loads a checkpoint and rebuilds the model

checkpoint_name = 'checkpoint_1.pth'

def load_checkpoint(filepath):
    checkpoint = torch.load(filepath)
    
    model_klass = getattr(models, checkpoint['model_name'])
    instance = model_klass(pretrained=True)
    
    model.load_state_dict(checkpoint['state_dict'])
    
    return model

model = torch.load(checkpoint_name)

# Inference for classification

Now you'll write a function to use a trained network for inference. That is, you'll pass an image into the network and predict the class of the flower in the image. Write a function called `predict` that takes an image and a model, then returns the top $K$ most likely classes along with the probabilities. It should look like 

```python
probs, classes = predict(image_path, model)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```

First you'll need to handle processing the input image such that it can be used in your network. 

## Image Preprocessing

You'll want to use `PIL` to load the image ([documentation](https://pillow.readthedocs.io/en/latest/reference/Image.html)). It's best to write a function that preprocesses the image so it can be used as input for the model. This function should process the images in the same manner used for training. 

First, resize the images where the shortest side is 256 pixels, keeping the aspect ratio. This can be done with the [`thumbnail`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.thumbnail) or [`resize`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.thumbnail) methods. Then you'll need to crop out the center 224x224 portion of the image.

Color channels of images are typically encoded as integers 0-255, but the model expected floats 0-1. You'll need to convert the values. It's easiest with a Numpy array, which you can get from a PIL image like so `np_image = np.array(pil_image)`.

As before, the network expects the images to be normalized in a specific way. For the means, it's `[0.485, 0.456, 0.406]` and for the standard deviations `[0.229, 0.224, 0.225]`. You'll want to subtract the means from each color channel, then divide by the standard deviation. 

And finally, PyTorch expects the color channel to be the first dimension but it's the third dimension in the PIL image and Numpy array. You can reorder dimensions using [`ndarray.transpose`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.transpose.html). The color channel needs to be first and retain the order of the other two dimensions.

In [ ]:
def process_image(image):
    ''' Scales, crops, and normalizes a PIL image for a PyTorch model,
        returns an Numpy array
    '''
    
    # TODO: Process a PIL image for use in a PyTorch model

To check your work, the function below converts a PyTorch tensor and displays it in the notebook. If your `process_image` function works, running the output through this function should return the original image (except for the cropped out portions).

In [ ]:
def imshow(image, ax=None, title=None):
    """Imshow for Tensor."""
    if ax is None:
        fig, ax = plt.subplots()
    
    # PyTorch tensors assume the color channel is the first dimension
    # but matplotlib assumes is the third dimension
    image = image.numpy().transpose((1, 2, 0))
    
    # Undo preprocessing
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    image = std * image + mean
    
    # Image needs to be clipped between 0 and 1 or it looks like noise when displayed
    image = np.clip(image, 0, 1)
    
    ax.imshow(image)
    
    return ax

## Class Prediction

Once you can get images in the correct format, it's time to write a function for making predictions with your model. A common practice is to predict the top 5 or so (usually called top-$K$) most probable classes. You'll want to calculate the class probabilities then find the $K$ largest values.

To get the top $K$ largest values in a tensor use [`x.topk(k)`](http://pytorch.org/docs/master/torch.html#torch.topk). This method returns both the highest `k` probabilities and the indices of those probabilities corresponding to the classes. You need to convert from these indices to the actual class labels using `class_to_idx` which hopefully you added to the model or from an `ImageFolder` you used to load the data ([see here](#Save-the-checkpoint)). Make sure to invert the dictionary so you get a mapping from index to class as well.

Again, this method should take a path to an image and a model checkpoint, then return the probabilities and classes.

```python
probs, classes = predict(image_path, model)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```

In [ ]:
def predict(image_path, model, topk=5):
    ''' Predict the class (or classes) of an image using a trained deep learning model.
    '''
    
    # TODO: Implement the code to predict the class from an image file

## Sanity Checking

Now that you can use a trained model for predictions, check to make sure it makes sense. Even if the validation accuracy is high, it's always good to check that there aren't obvious bugs. Use `matplotlib` to plot the probabilities for the top 5 classes as a bar graph, along with the input image. It should look like this:

<img src='https://github.com/laknath/pytorch_challenge/blob/master/assets/inference_example.png?raw=1' width=300px>

You can convert from the class integer encoding to actual flower names with the `cat_to_name.json` file (should have been loaded earlier in the notebook). To show a PyTorch tensor as an image, use the `imshow` function defined above.

In [ ]:
# TODO: Display an image along with the top 5 classes